
from __future__ import annotations

from fastapi import APIRouter
from pydantic import BaseModel, Field

from ..config import settings
from ..services import genai as svc

router = APIRouter(prefix="/genai", tags=["assistant"])


class AskRequest(BaseModel):
    question: str = Field(
        min_length=1,
        description="A natural-language question about the forecasts or model.",
        examples=["Explain this forecast in plain language"],
    )
    store_id: str | None = Field(
        default=None, description="Selected store, e.g. CA_3. Supplies series context.")
    item_id: str | None = Field(
        default=None, description="Selected item, e.g. FOODS_3_090.")
    level: str = Field(default="total", description="Aggregation level for scope questions.")
    node_id: str = Field(default="ALL", description="Node within that level.")


class AskResponse(BaseModel):
    answer: str
    intent: str = Field(description="Which family of data was retrieved to answer.")
    model: str
    grounded: bool = Field(
        description="True when every figure in the answer traces to the supplied context.")
    ungrounded_numbers: list[float] = Field(
        default_factory=list,
        description="Figures with no source in the context. Should be empty.")
    injection_suspected: bool = Field(
        description="True when the question matched a prompt-injection pattern.")
    context_keys: list[str] = Field(
        description="Top-level keys of the context the model was given.")
    elapsed_ms: int
    disclaimer: str
    truncated: bool = Field(
        default=False,
        description="True when the reply hit the output token limit and was cut short.")
    refused: bool = Field(
        default=False,
        description=("True when local policy answered the question and NO AI "
                     "provider was called at all."))
    refusal_category: str | None = Field(
        default=None,
        description=("Which policy applied: secret_extraction, "
                     "instruction_override, forecast_mutation, model_mutation."))


DISCLAIMER = (
    "Generated by an AI assistant from verified backend data. Every number it "
    "quotes is computed by the forecasting system, not by the assistant. The "
    "model is frozen and the assistant cannot change any forecast."
)

REFUSAL_DISCLAIMER = (
    "Answered by this service's own policy layer. No AI provider was called, so "
    "this response is deterministic and does not depend on any external service "
    "being available."
)


@router.get("/status", summary="Is the AI assistant configured here?")
def status() -> dict:
    return svc.status()


@router.post("/ask", response_model=AskResponse,
             summary="Ask a question about the forecasts")
def ask(body: AskRequest) -> AskResponse:
    reply = svc.ask(
        question=body.question,
        store_id=body.store_id,
        item_id=body.item_id,
        level=body.level,
        node_id=body.node_id,
    )
    return AskResponse(
        answer=reply.answer,
        intent=reply.intent,
        model=reply.model,
        grounded=reply.grounded,
        ungrounded_numbers=reply.ungrounded_numbers,
        injection_suspected=reply.injection_suspected,
        context_keys=reply.context_keys,
        elapsed_ms=reply.elapsed_ms,
        truncated=reply.truncated,
        disclaimer=REFUSAL_DISCLAIMER if reply.refused else DISCLAIMER,
        refused=reply.refused,
        refusal_category=reply.refusal_category,
    )


@router.post("/context-preview", summary="Show the context a question would use")
def context_preview(body: AskRequest) -> dict:
    from ..services import genai_context

    ctx = genai_context.resolve(
        body.question, body.store_id, body.item_id, body.level, body.node_id)
    import json

    return {
        "intent": ctx["intent"],
        "context": ctx,
        "size_bytes": len(json.dumps(ctx, default=str)),
        "note": ("This is everything the assistant is given. It has no other "
                 "access to the data."),
    }
