
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent

DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"

SALES_EVAL_CSV = RAW_DIR / "sales_train_evaluation.csv"
SALES_VALID_CSV = RAW_DIR / "sales_train_validation.csv"
CALENDAR_CSV = RAW_DIR / "calendar.csv"
SELL_PRICES_CSV = RAW_DIR / "sell_prices.csv"
SAMPLE_SUBMISSION_CSV = RAW_DIR / "sample_submission.csv"

PROCESSED_PARQUET = PROCESSED_DIR / "sales_long_full.parquet"

EXPERIMENTS_ROOT = PROJECT_ROOT / "experiments"
EXPERIMENTS_DIR = EXPERIMENTS_ROOT / "registry"
ARTIFACTS_DIR = EXPERIMENTS_ROOT / "artifacts"

MODELS_ROOT = PROJECT_ROOT / "models"
MODELS_DIR = MODELS_ROOT / "experiments"
CHAMPION_DIR = MODELS_ROOT / "champion"

PREDICTIONS_ROOT = PROJECT_ROOT / "predictions"
PREDICTIONS_DIR = PREDICTIONS_ROOT / "validation"
FINAL_FORECAST_DIR = PREDICTIONS_ROOT / "final_forecast"

REPORTS_DIR = PROJECT_ROOT / "reports"

DOCS_DIR = PROJECT_ROOT / "docs"

for _d in (ARTIFACTS_DIR, REPORTS_DIR, MODELS_DIR, CHAMPION_DIR, EXPERIMENTS_DIR,
           PREDICTIONS_DIR, FINAL_FORECAST_DIR):
    _d.mkdir(parents=True, exist_ok=True)


N_SERIES = 30_490
N_ITEMS = 3_049
N_STORES = 10
N_STATES = 3
N_DEPTS = 7
N_CATS = 3

N_HISTORY_DAYS = 1_941
N_CALENDAR_DAYS = 1_969
N_PRICE_WEEKS = 282

EXPECTED_TOTAL_UNITS = 66_927_173
EXPECTED_ZERO_CELLS = 40_241_819
EXPECTED_MAX_SALES = 763


HORIZON = 28


LAST_KNOWN_DAY_IDX = N_HISTORY_DAYS - 1

FINAL_FORECAST_ORIGIN_IDX = LAST_KNOWN_DAY_IDX

VALIDATION_ORIGIN_IDX = 1912

ALT_VALIDATION_ORIGIN_IDXS = [1912 - 28, 1912 - 56, 1912 - 84]


LAGS = [1, 7, 14, 28]
ROLLING_WINDOWS = [7, 28]
PRICE_AVG_WINDOW_WEEKS = 8

RANDOM_SEED = 42
